language: node_js
node_js:
- 12
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  skip_cleanup: true
  api_key:
    secure: aW9//snGZ0R8QoI5NVNVIm3ngxJ3L57SWeUWD4Pv1YR1nsMVQ2mzOM3v2dRQsgD8o9XqLvtzIZgKNOsYAXvt1eKb40kk1gBwxeyXWySbXq4I6DKV/4higw0lqcUs+nG2G2nUGFFwUq+s1cXEo0imdJX9P5uIFig3ZM+cP1ARGxyEoUS/oTtBEtYQuDFWnmHyY7ZbzNDKHzXgKOUsbSEpJ09wcQQdsx7BTQaI04ZO2w7VitySLHmXIcdeU4NdsMUsCDifHf+/AQV3KmwhK/eSE2E8kLj8pTOVCI0Kx0BWBAuwznVoj6ch7bySLwr05Dt3QrgAHGZh0o18ENdA5t00pzq73NbAAE3kDdoMVW9fs7lR+79ywRoPM23+ktFckOZyGDCdiM1VqIp/dh7RRWk5P5Lp44GFGh52FPmeM5Q8vKI4xP8i5W8bBMG3kse80Wo7izJfGTFGowl2yASElDUW/Nao/voLM0RNPnJ2BcM//O56OfMMhcfHxefkaYWVjBSZS3CfwYq1rIJTIyRUQaSkhlXetHVSDUZbb7EK4Z62lBzAWsEWuJesQhdMLqnt1t6fdvZtcpMC6MhRfI2qGKIWt40/lxaUMIZM6ZPg/zLVtFGmAURIVHl/9EVAVIC6OtX3VZr2wTpXgauWaqaiqPV+WstBf6nUmf/vTTKnOcbYj9c=
  on:
    tags: true
    repo: technicallyjosh/pino-http-send
